clear all
clear classes
clear all
close all

% for repeatability while testing
rng('default')

%% Set Up the Biology
% Grass
myGrass = plant('Name', 'Grass', ...
    'FeedsOn', "", ...
    'Colour', [70, 242, 128] / 255);

% Sheep
mySheep = animal('Name', 'Sheep', ...
    'FeedsOn', 'Grass', ...
    'Colour', [255, 255, 255] / 255, ...
    'LineColour', [200, 200, 200] / 255, ...
    'ProbReproduce', 0.04, ...
    'GainFromFood', 4, ...
    'Energy', 1, ...
    'Marker', 'o',...
    'Coordinate', [0, 0]);
nSheep = 100;

% Dingos
myDingos = animal('Name', 'Dingo', ...
    'FeedsOn', 'Sheep', ...
    'Colour', [0, 0, 0] / 255, ...
    'ProbReproduce', 0.05, ...
    'GainFromFood', 20, ...
    'Energy', 1, ...
    'Marker', 'x',...
    'Coordinate', [0, 0]);
nDingos = 50;

%% Set Up The World
mySim = world({myGrass, mySheep, myDingos}, ...
    [Inf, nSheep, nDingos], ...
    'nSteps', 250);

%% Plot a food web
plotFoodWeb(mySim)

%% Run
run(mySim);