clear all
clear classes
clear all
close all

% for repeatability while testing
% rng('default')

nSteps = 2000;

%% Set Up the Biology
% Grass
myGrass = plant('Name', 'Grass', ...
    'FeedsOn', "", ...
    'Energy', 1, ...
    'Colour', [70, 242, 128] / 255);

% Sheep
mySheep = animal('Name', 'Sheep', ...
    'FeedsOn', 'Grass', ...
    'Colour', [240, 240, 240] / 255, ...
    'LineColour', [200, 200, 200] / 255, ...
    'ProbReproduce', 0.04, ...
    'GainFromFood', 4, ...
    'Energy', 1, ...
    'Marker', 'o',...
    'Coordinate', [0, 0]);
nSheep = 100;

% Dingos
myDingos = animal('Name', 'Dingo', ...
    'FeedsOn', 'Sheep', ...
    'Colour', [0, 0, 0] / 255, ...
    'ProbReproduce', 0.05, ...
    'GainFromFood', 20, ...
    'Energy', 1, ...
    'Marker', 'x',...
    'Coordinate', [0, 0]);
nDingos = 50;

%% Run
while true
    try
        close all
        mySim = world({myGrass, mySheep, myDingos}, ...
            [Inf, nSheep, nDingos], ...
            'nSteps', nSteps, ...
            'printPlots', true);
        run(mySim);
    catch
        continue
    end
    if mySim.currTimeStep == nSteps
        break
    end
end